name: flutter_application
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.4.6
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.2
  google_maps_flutter: ^2.0.6
  geocoding: ^3.0.0
  geolocator: ^13.0.3
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.1.5
  flutter_rating_bar: ^4.0.1
  flutter_paypal_payment: ^1.0.8
  supabase: ^2.3.0
  supabase_flutter: ^2.2.0
  url_launcher: ^6.1.11
  flutter_facebook_auth: ^6.1.1
  intl: ^0.18.1 
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  cached_network_image: ^3.3.1
  image: ^4.0.15
  flutter_polyline_points: ^2.0.0
 
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/hamburger.png
    - assets/logo.jpeg
    - assets/esewa.png
    - assets/khalti.png
    - assets/cash.png
    - assets/payment.png
    - assets/food.png
    - assets/email.png
    - assets/icons/drink.jpg
    - assets/icons/breakfast.jpg
    - assets/icons/snacks.jpg
    - assets/icons/Lunch.jpg
    - assets/icons/Dinner.jpg
    - assets/avatar/image1.jpg
    - assets/avatar/image2.jpg
    - assets/avatar/image3.jpg
    - assets/avatar/image4.jpg
    - assets/avatar/image5.jpg
    - assets/restaurant_location.png



  fonts: 
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
         
  
    
    
    
  uses-material-design: true

  